### ISSUE TITLE
Merging the PRs 

### ISSUE THREAD

**Issue by edyoshikun** [czbiohub-sf/shrimPy#112]
The mantis PRs should be merged in this order after testing:

Data processing:
- [x] Bugfix #134 <--
- [x] Registration #102 
- [x] Stabilization #128 <--
- [ ] Segmentation #106 
- [x] Merging datasets #107 

New features:
- [ ] Stitching #137 
- [ ] Copy&Paste example #140 
- [x] Concatenate CLI #145 
- [x] PSF Benchmarking #131 <--
- [ ] PSF Decon #130 <--
- [ ] Illumination correction and denoising #109 <-- (move denoising to Viscy)

**Comment by mattersoflight** [comment]
The pytorch implementation of denoising models: https://github.com/dl4mia/02_regression/blob/main/02_Noise2Void/n2v_solution.ipynb
