### ISSUE TITLE
Name our new image processing library

### ISSUE THREAD

**Issue by talonchandler** [czbiohub-sf/shrimPy#151]
Tomorrow we will start moving the `shrimpy` image analysis utilities to a new repository. Our rough vision for this repository is that it will provide CLI utilities for common image analysis tasks. We will start the repository with `deskew`, `affine`, `decon`, `stitch`, and `stabilize` utilities. These utilities were originally developed for the mantis project, and we've found them valuable across our projects. 

Our working name for this project has been `iphub` for "image processing hub", but we've found that this more commonly evokes "intellectual property hub". 

Let's use this issue to suggest and discuss potential names. 

I'll suggest `imghub` and `imagehub`. 

@mattersoflight @ieivanov @edyoshikun @ziw-liu @Soorya19Pradeep @JoOkuma please tag anyone else who may be interested.

**Comment by edyoshikun** [comment]
At the start of the internship Aaron and I had created https://github.com/czbiohub-sf/ImgFlow for us to documents the features, however, we never got to add anything to it. 

I vote for `imghub` or `imgFlow`.

**Comment by ziw-liu** [comment]
Not a big deal, but there are 59 `imghub`s, 159 `imagehub`s, and 6 `imgflow`s on github.

Going from `img` or `image` to `mim` (Microscopy IMage) helps de-duplicate GH and PyPI names.

**Comment by mattersoflight** [comment]
`NDhub`?

**Comment by talonchandler** [comment]
I'm hearing `mimhub` from @ziw-liu! I like it.

**Comment by ieivanov** [comment]
How about hubbii  - HUB for Bio Image Interpretation?

**Comment by talonchandler** [comment]
Closing...we landed on [`biahub`](https://github.com/czbiohub-sf/biahub).
